version: "2"
services:
    frontend:
       build: "./frontend"
       ports: 
           - 3000:3000
       volumes:
           - "./frontend:/app"
           - "/app/node_modules"
       environment:
           - NODE_ENV development
    backend:
       build: "./backend"
       ports:
           - "8000:8000"
       depends_on:
           - "db"
           - "redis"
       volumes:
           - "./backend/aplikacja_zapisowa:/app"
    db:
       image: "postgres:latest"
       volumes:
           - "aplikacja-zapisowa_postgress-volume"
    redis:
       image: "redis:5-alpine"
