version: "2"
services:
    frontend-user:
       build: "./frontend-user"
       ports: 
           - 3000:3000
       volumes:
           - "./frontend-user:/app"
           - "/app/node_modules"
       environment:
           - NODE_ENV=development
    frontend-admin:
       build: "./frontend-admin"
       ports: 
           - 3001:3000
       volumes:
           - "./frontend-admin:/app"
           - "/app/node_modules"
       environment:
           - NODE_ENV=development
    backend:
       build: "./backend"
       ports:
           - "8000:8000"
       depends_on:
           - "db"
           - "redis"
       volumes:
           - "./backend/aplikacja_zapisowa:/app"
    db:
      image: postgres:latest
      environment:
        - POSTGRES_DB=db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=passwd123
      volumes:
        - pgdata:/var/lib/postgresql/data
    redis:
       image: "redis:5-alpine"
volumes:
  pgdata: