# Generated by Django 2.1 on 2018-10-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0002_room_cur_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='vacancies',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
