# Generated by Django 2.1 on 2018-11-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0003_room_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.PositiveSmallIntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Test', max_length=30),
            preserve_default=False,
        ),
    ]
