# Generated by Django 2.1 on 2018-10-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0003_auto_20181013_2012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('index', 'event')},
        ),
    ]
