# Generated by Django 2.1 on 2019-02-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0004_auto_20181113_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='organiser',
        ),
    ]
