# Generated by Django 2.1 on 2019-02-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0005_auto_20190226_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organiser',
            new_name='organizer',
        ),
    ]
