# Generated by Django 2.1 on 2019-02-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0006_auto_20190226_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='organiser',
        ),
    ]
