# Generated by Django 2.1 on 2019-03-09 01:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0006_auto_20190226_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_people',
        ),
        migrations.AddField(
            model_name='event',
            name='accommodation',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='beginning_date',
            field=models.DateField(default='2013-09-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='trololo', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='ending_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
