# Generated by Django 2.1 on 2019-03-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0007_auto_20190309_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='photo',
            new_name='image',
        ),
    ]
