# Generated by Django 2.1 on 2019-03-11 23:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0008_auto_20190311_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/images'), upload_to=''),
        ),
    ]
