# Generated by Django 2.1 on 2019-03-20 09:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0009_auto_20190311_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='/app/enrolmentpanel/static/images'), upload_to=''),
        ),
    ]
