# Generated by Django 2.1 on 2019-03-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0010_auto_20190320_0956'),
        ('enrolmentpanel', '0007_auto_20190226_2054'),
    ]

    operations = [
    ]
