# Generated by Django 2.1 on 2019-03-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0011_merge_20190325_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organiser',
            new_name='organizer',
        ),
    ]
