# Generated by Django 2.1 on 2019-04-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0012_auto_20190325_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser',
            name='name',
            field=models.CharField(default='Jamnik', max_length=30),
            preserve_default=False,
        ),
    ]
