# Generated by Django 2.1 on 2019-04-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0014_auto_20190411_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='jamnik@kupa.pl', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('N', 'Not registered'), ('S', 'Solo registered'), ('G', 'Group registered')], default='N', max_length=1),
        ),
    ]
