# Generated by Django 2.1 on 2019-04-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0015_auto_20190419_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
