# Generated by Django 2.1 on 2019-04-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolmentpanel', '0015_auto_20190419_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
